import type { TestCase } from '../types/analysis';
import { generateReproSteps } from './reproSteps';
import { getConciseReason } from '../components/FailureSummary';

function truncate(s: string, max: number): string {
  return s.length > max ? `${s.slice(0, max - 3)}...` : s;
}

/** The concrete, scannable symptom for the title — prefers the Expected/Received
 * diff (most specific), falls back to the first sentence of the analysed cause,
 * then the concise reason. Never just the raw test name — that belongs at the end. */
function extractSymptom(tc: TestCase): string {
  if (tc.evidenceContext?.expected || tc.evidenceContext?.received) {
    return `expected "${tc.evidenceContext.expected ?? '—'}" but got "${tc.evidenceContext.received ?? '—'}"`;
  }
  const cause = tc.symptomVsCause?.cause;
  if (cause) {
    const firstSentence = cause.split(/(?<=[.!?])\s/)[0];
    return truncate(firstSentence, 100);
  }
  return truncate(getConciseReason(tc), 100);
}

/**
 * A title a senior SDET would actually want to scan in a backlog: leads
 * with the failure category and the concrete symptom, test name last for
 * context/searchability — not just the test name restated.
 */
export function generateTicketTitle(tc: TestCase): string {
  const category = tc.category || 'Failure';
  const symptom = extractSymptom(tc);
  const testLabel = truncate(tc.name, 90);
  return `[${category}] ${symptom} — ${testLabel}`.slice(0, 250);
}

/**
 * Markdown ticket body in standard bug-report structure — Preconditions,
 * Steps to Reproduce, Expected Result, Actual Result — rather than one
 * merged list. Renders fully in GitHub Issues/Linear; pastes into Jira's
 * description field as readable structured text.
 */
export function generateTicketBody(tc: TestCase): string {
  const repro = generateReproSteps(tc);
  const lines: string[] = [];

  lines.push('## Summary');
  lines.push(getConciseReason(tc));
  lines.push('');
  lines.push(`**Test:** ${tc.name}`);
  if (tc.suite) lines.push(`**Suite:** ${tc.suite}`);
  lines.push(`**Category:** ${tc.category || 'Unknown'}  **Severity:** ${tc.severity || 'LOW'}`);
  if (tc.isHookFailure) lines.push(`**Setup/hook failure** — may be blocking other tests in this suite`);
  if (tc.isFlaky) lines.push(`**Flaky:** retry attempts produced different results`);
  if (tc.isCascading) lines.push(`**Cascading:** part of group \`${tc.cascadeGroupId}\` — the fix may unblock other failing tests too`);
  if (tc.attemptCount && tc.attemptCount > 1) lines.push(`**Attempts:** ${tc.attemptCount}`);
  lines.push('');

  if (repro.preconditions.length > 0) {
    lines.push('## Preconditions');
    repro.preconditions.forEach((p) => lines.push(`- ${p}`));
    lines.push('');
  }

  lines.push('## Steps to Reproduce');
  repro.steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
  lines.push('');

  lines.push('## Expected Result');
  lines.push(repro.expectedResult);
  lines.push('');

  lines.push('## Actual Result');
  lines.push(repro.actualResult);
  lines.push('');

  if (tc.symptomVsCause?.cause) {
    lines.push('## Analysed Root Cause');
    lines.push(tc.symptomVsCause.cause);
    lines.push('');
  }

  if (tc.relatedLinks.length > 0) {
    lines.push('## Evidence Links');
    tc.relatedLinks.forEach((l) => lines.push(`- [${l.label}](${l.url})`));
    lines.push('');
  }

  if (tc.logEvidenceQuote) {
    lines.push('## Log Evidence');
    lines.push('```');
    lines.push(tc.logEvidenceQuote);
    lines.push('```');
    lines.push('');
  }

  lines.push('---');
  lines.push(`_${tc.id} · generated by Jenkins Log Analyzer_`);

  return lines.join('\n');
}
